package util

import org.hamcrest.MatcherAssert
import org.hamcrest.Matchers.contains
import org.hamcrest.Matchers.`is`
import org.junit.Test

class Array2dTest {

    @Test
    fun `find operator finds things`() {
        val map = CharArray2d("""
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
        """.trimIndent().lines())

        val sequence = map.find('0')
        MatcherAssert.assertThat(sequence.first(), `is`(Point2d(8,1)))
        MatcherAssert.assertThat(sequence.toList(), contains(Point2d(8,1),Point2d(5,2), Point2d(7,3), Point2d(4,4)))
    }
}